const en = {
  promoBar: {
    items: [
      'v4.9.1 — CC-native /auto orchestration · session-scoped workflow state · Codex + zh-Hans i18n',
      'Auto-routed subagents → Agent Teams, decided per subtask',
      'Composing ECC · Superpowers · GSD · gstack',
      'Apache-2.0 · Node 22+ · Cross-platform',
      'Star us on GitHub →',
    ],
  },
  nav: {
    docs: 'Docs',
    github: 'GitHub',
    npm: 'npm',
  },
  hero: {
    versionPill: 'v4.9.1 · 100+ capabilities composed',
    h1: 'The package manager for AI coding harnesses',
    positioning:
      'More than a package manager — a composition orchestrator. It assembles the best of the open-source ecosystem into one executable engine, wired by the three-layer BDD → SDD → TDD methodology.',
    tagline:
      'harnessed is an orchestration brain + prompt library, not an execution engine. Slash-command bodies (generated by `harnessed setup`) drive CC-native subagent spawn through three fast, pure-function CLIs — `harnessed gates` (which sub-workflows fire), `harnessed prompt` (spawn-ready prompt for a sub), and `harnessed checkpoint` (record progress). The actual spawn, Agent Teams, ralph-loop, and clarification round-trips all run in the Claude Code main session with native tools. `harnessed run` is retained for CI/headless only.',
    ctaStart: 'Get Started',
    ctaGitHub: 'View on GitHub',
    meta: 'Apache-2.0 · Node 22+ · Cross-platform',
  },
  whyCards: {
    heading: 'Why harnessed',
    subheading: 'Three principles built into every workflow.',
    card1: {
      title: 'Composition over vendoring',
      body: 'Never fork upstream. Describe install + check in a manifest, and harnessed composes the best of the open-source ecosystem (Superpowers, GSD, gstack, ECC, …) into one runnable workflow — always on the latest upstream, painlessly: just update to get it.',
    },
    card2: {
      title: '5-stage cadence built-in',
      body: 'Discuss → Plan → Task → Verify → Ship, with optional Research and Retro, composed into every loop and closed by an automatic Learn cycle. Or run `/auto` to drive the full pipeline in one shot.',
    },
    card3: {
      title: 'Dogfood-first methodology',
      body: 'Every workflow is validated against its own definition. The same discipline that ships harnessed itself.',
    },
  },
  threeLayerStack: {
    heading: 'Three nested loops, not three phases',
    subheading:
      "harnessed's three-layer stack is a software-engineering implementation of the established BDD → SDD → TDD nesting. Three loops, each answering a different question. harnessed composes the open-source ecosystem into each loop — and the components partially overlap, which is exactly what a composition orchestrator has to arbitrate.",
    colLayer: 'Layer / Loop',
    colQuestion: 'Question it answers',
    colComposed: 'Composed from (overlapping)',
    layers: [
      {
        num: '①',
        name: 'Behavior',
        loop: 'BDD',
        question: 'What to build, and how we know it is done.',
        composed: 'gstack /office-hours governance · GSD discuss · superpowers brainstorming → acceptance criteria',
      },
      {
        num: '②',
        name: 'Spec',
        loop: 'SDD',
        question: 'How it is structured.',
        composed: 'GSD plan-phase → requirements / design / tasks · contracts (Spec Kit / ECC patterns)',
      },
      {
        num: '③',
        name: 'Implementation',
        loop: 'TDD',
        question: 'Does it actually work.',
        composed: 'superpowers TDD red-green · subagent execution · GSD verify-work · ralph-loop completion',
      },
    ],
    nested: {
      label: 'Nested lenses',
      body: "The loops are nested lenses, not phases. Cucumber's BDD-outer + TDD-inner double-loop, extended in the GenAI era with an SDD spec ring → a triple-loop. harnessed is the linear-cadence realization of this triple-loop — the full routed graph is its evolution path. The default traversal is outer → inner; three feedback edges ship today: Verify → Task (a failed check pushes work back), a subagent's STATUS: NEEDS_CLARIFICATION on a gray area, and each shipped cycle's learnings feeding the next Discuss. Finer-grained structured returns — a contract contradiction routing to Spec, a requirement ambiguity to Behavior — are on the roadmap, not yet shipped.",
    },
    intersections: {
      label: 'Components intersect',
      body: 'The overlap is the point — it is what the composition orchestrator arbitrates.',
      items: [
        { name: 'GSD', body: 'is the backbone, threading all three rings — discuss, plan, verify.' },
        { name: 'gstack', body: 'spans Behavior + Review.' },
        { name: 'superpowers', body: 'spans Behavior (brainstorm) + Implementation (TDD).' },
      ],
    },
    crossCutting: {
      label: 'Cross-cutting disciplines',
      body: 'Two disciplines run through every layer.',
      items: [
        { name: 'karpathy principles', body: 'how to code — smallest viable change, surgical edits.' },
        { name: 'mattpocock moves', body: 'on-demand tools, summoned per situation.' },
      ],
    },
    runtime: {
      label: 'Mapped to the runtime',
      body: 'Discuss = Behavior · Plan = Spec · Build = Implementation · Verify + Ship close the loop with evidence gates.',
    },
  },
  orchestration: {
    heading: 'Parallelism, decided per subtask',
    subheading:
      '`harnessed setup` auto-enables Agent Teams. A routing gate then picks the right execution tier for every subtask — no manual fan-out, no guesswork.',
    tiers: [
      {
        tag: 'downgrade',
        name: 'Main session',
        cond: '< 20 lines · single query',
        body: 'Trivial work stays inline. No spawn, no token overhead.',
      },
      {
        tag: 'default',
        name: 'Subagent fan-out',
        cond: '≤ 3 parallel · no cross-talk',
        body: 'Independent research, verify, and review tasks fan out in isolated context.',
      },
      {
        tag: 'upgrade',
        name: 'Agent Teams',
        cond: '5 triggers · SendMessage',
        body: 'Teammates that align a contract, debate hypotheses, or share a task list escalate to a real team.',
      },
    ],
    wrapper: {
      label: 'orthogonal wrapper',
      name: 'ralph-loop',
      body: 'Wraps any tier and holds it to a verbatim COMPLETE completion-promise.',
    },
    footnote:
      '12 judgment gates mechanize your AI-collaboration rules — parallelism, TDD triggers, three-layer clarification — turning static conventions into a routing engine.',
  },
  workflowSection: {
    heading: 'One command. Five stages. Zero boilerplate.',
    subheading: 'Each stage composes proven tools from across the AI coding harness ecosystem.',
    stages: {
      research: { name: 'research', role: 'multi-source RAG' },
      discuss: { name: 'discuss', role: '3-layer gates' },
      plan: { name: 'plan', role: 'task_plan.md' },
      task: { name: 'task', role: 'clarify·code·test·deliver' },
      verify: { name: 'verify', role: '7 sub-checks' },
      ship: { name: 'ship', role: 'release-preflight → tag-ready' },
      retro: { name: 'retro', role: 'lessons captured' },
    },
    optional: 'opt',
  },
  workflowTable: {
    heading: '27 composable workflows, 100+ capabilities',
    subheading: 'From research to ship, each backed by a typed manifest.',
    colCommand: 'Command',
    colScope: 'Scope',
    colCaps: 'Capabilities',
    rows: [
      { cmd: '/auto', scope: 'super-master', caps: '6-stage pipeline' },
      { cmd: '/research', scope: 'standalone', caps: 'tavily·exa·ctx7' },
      { cmd: '/discuss', scope: 'stage gate', caps: 'strategic·phase·subtask' },
      { cmd: '/plan', scope: 'stage gate', caps: 'architecture·phase' },
      { cmd: '/task', scope: 'per-subtask', caps: 'clarify·code·test·deliver' },
      { cmd: '/verify', scope: 'stage gate', caps: '7 sub conditional' },
      { cmd: '/ship', scope: 'stage gate', caps: 'release-preflight·gstack-ship' },
      { cmd: '/retro', scope: 'post-ship', caps: 'gstack·persist' },
      { cmd: '/tdd', scope: 'discipline', caps: 'red-green-refactor' },
      { cmd: '/ralph-loop', scope: 'wrapper', caps: 'completion-promise' },
    ],
    githubLink: 'View all workflows on GitHub →',
  },
  quickstart: {
    heading: 'Get started in 60 seconds',
    subheading: 'No config files. No manual scaffolding. Just three commands.',
    steps: [
      {
        num: '1',
        title: 'Install',
        cmd: 'npm install -g harnessed',
        caption: 'Pulls the latest stable from npm.',
      },
      {
        num: '2',
        title: 'Setup',
        cmd: 'harnessed setup',
        caption: 'Auto-enables Agent Teams, user locale, and MCP discovery.',
      },
      {
        num: '3',
        title: 'Compose',
        cmd: '/auto research a new feature',
        caption: 'Run inside your AI coding agent. The 6-stage pipeline takes over.',
      },
    ],
  },
  communityStats: {
    heading: 'Join the harness ecosystem',
    stats: [
      { value: '100+', label: 'Capabilities composed (ECC · Superpowers · GSD · gstack)' },
      { value: '27', label: 'Workflows shipped' },
      { value: 'v4.9.1', label: 'Latest release · Apache-2.0' },
    ],
    links: {
      discussions: 'GitHub Discussions →',
      issues: 'Issues →',
      releases: 'Releases →',
    },
  },
  faq: {
    heading: 'FAQ',
    subheading: 'Common questions, plain answers.',
    items: [
      {
        q: 'What is harnessed?',
        a: 'harnessed is the package manager and composition orchestrator for AI coding harnesses. It installs, composes, and runs workflows that combine Skills, MCP servers, and other harness packs through a typed manifest — without vendoring upstream code.',
      },
      {
        q: 'Which AI coding agent does it run in?',
        a: "harnessed runs inside an AI coding agent. Claude Code is the primary target — after `harnessed setup`, slash commands like `/auto` and `/discuss` become available (new to Claude Code? see anthropic.com/claude/code). Codex and other harnesses are supported via the cross-harness platform layer.",
      },
      {
        q: 'How does composition work without vendoring?',
        a: 'Each harness pack ships a manifest that describes install steps, capability metadata, and integration points. harnessed reads these manifests, validates compatibility, and stitches the upstream tools together at runtime — so you always run the official upstream, never a stale fork.',
      },
      {
        q: "What's the difference between /auto and individual stage commands?",
        a: '`/auto` runs the full 6-stage pipeline end-to-end with one prompt. Individual stage commands (`/discuss`, `/plan`, `/task`, `/verify`, etc.) give you fine-grained control when you only need part of the cadence.',
      },
      {
        q: 'Does it spawn subagents automatically?',
        a: '`harnessed setup` auto-enables Agent Teams, and a parallelism gate decides the tier per subtask: trivial work stays in the main session, independent tasks fan out as subagents (≤ 3, isolated context), and work that needs cross-talk — contract alignment, hypothesis debate, shared task lists — escalates to a real Agent Team. ralph-loop can wrap any tier to hold it to a verbatim COMPLETE.',
      },
      {
        q: 'Can I write my own harness pack?',
        a: 'Yes. The manifest schema is published in the repo at `schemas/manifest.v1.schema.json` (point your YAML language server at it). Author a manifest pointing at any installable upstream — npm package, git repo, custom skill — and harnessed will treat it as a first-class composable unit.',
      },
    ],
  },
  footer: {
    tagline: 'AI coding harness package manager + composition orchestrator.',
    resources: 'Resources',
    community: 'Community',
    links: {
      github: 'GitHub',
      npm: 'npm',
      changelog: 'Changelog',
      docs: 'Docs',
      discussions: 'Discussions',
      issues: 'Issues',
      twitter: 'Twitter',
    },
    license: 'Apache-2.0 License © 2026 easyinplay',
    madewith: 'Made with discipline',
  },
}

export default en
export type Dict = typeof en
